### ISSUE TITLE
Attempting to edit with vscode now fails silently

### ISSUE THREAD

**Issue by inmanturbo** [spatie/laravel-ignition#169]
Still get the confirmation dialog asking to open vscode url handler, however it no longer opens the file in vscode.

I can't find any related errors in the logs or output for vscode, or any of the laravel applications I'm attempting to use this with.

vscode `1.84.1
2b35e1e6d88f1ce073683991d1eff5284a32690f
x64`
Ubuntu `22.04.3 LTS`
Laravel Framework `10.31.0`
PHP `8.2.12`

**Comment by lakuapik** [comment]
I think it is related to vscode issue https://github.com/microsoft/vscode/issues/197541.

**Comment by inmanturbo** [comment]
Thanks. It looks like it's fixed over there in a subsequent release. I'll try the update as soon as I get a chance.

**Comment by freekmurze** [comment]
Closing as it's fixed in viscode itself.

**Comment by saschalalala** [comment]
Hey everyone, to me it looks like the issue still persists. I am running the latest VS Code version on Mac (Version: 1.84.2) and it says in the Output tab in VS Code

> If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

I temporarily fixed it for me by monkeypatching ignition.js (which is part of the ignition package I think) and removing `encodeUriComponent` in the path replacement there like this:

```javascript
url: r.url
      .replace("%path", e)
      .replace("%line", encodeURIComponent(t)),
```

I also had to change the vscode config here: https://github.com/spatie/ignition/blob/main/src/Config/IgnitionConfig.php#L188 to 

```php
 'vscode' => [
      'label' => 'VS Code',
      'url' => 'vscode://file%path:%line',
  ],
```

in order to make the feature work for me again.

Can anyone relate or am I missing something?

**Comment by inmanturbo** [comment]
> Hey everyone, to me it looks like the issue still persists. I am running the latest VS Code version on Mac (Version: 1.84.2) and it says in the Output tab in VS Code
> 
> > If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
> 
> I temporarily fixed it for me by monkeypatching ignition.js (which is part of the ignition package I think) and removing `encodeUriComponent` in the path replacement there like this:
> 
> ```js
> url: r.url
>       .replace("%path", e)
>       .replace("%line", encodeURIComponent(t)),
> ```
> 
> I also had to change the vscode config here: https://github.com/spatie/ignition/blob/main/src/Config/IgnitionConfig.php#L188 to
> 
> ```
>  'vscode' => [
>       'label' => 'VS Code',
>       'url' => 'vscode://file%path:%line',
>   ],
> ```
> 
> in order to make the feature work for me again.
> 
> Can anyone relate or am I missing something?

Yes, this issue persists for me too on both my Macbook and my Linux desktop VSCode 1.84.2

**Comment by saschalalala** [comment]
@inmanturbo Can you reopen the issue or is this still a VS code problem?

**Comment by inmanturbo** [comment]
@saschalalala I believe it could be solved in a PR here using the fix you've outlined above, but I don't think I can reopen this issue without duplicating it. @freekmurze ?

It would be very nice to have this feature back and working when using VSCode. It makes quite a difference when manual testing.

**Comment by saschalalala** [comment]
@inmanturbo I am not super optimistic about the change I patched. 

1. I think it is a VSCode specific thing so that ignition.js must keep track of the editor when it creates the file url which it doesn't need to do at the moment. 
2. I don't know if it is a Mac specific thing. You are using Ubuntu, right? Can you check if my patch works for you, too? Still not sure about windows then. Absolute paths in windows start with something like C:\\ and not /
3. I am not sure where to make that change in the source since I wasn't able yet to read through the ignition.js source code and only patched the compiled version inside my vendor directory. 
4. perhaps I am overthinking this and there is a much easier fix that one of the maintainers of the projects know about. 

5. Perhaps we should start a discussion since I can imagine that no one reads answers in a closed issue :D

**Comment by inmanturbo** [comment]
This is still ongoing. I'm not confident much will come of a discussion either, but could we convert it to one so we can at least perhaps see if others are also experiencing this issue?. The patch in vscode code base linked above did not fix this so why is it closed?

**Comment by lakuapik** [comment]
With this thing still occuring for some people. just a thought, @freekmurze would it be possible feature if there is a way to append/update to `editor_options` via the config file?

https://github.com/spatie/ignition/blob/5bd834e7b98dfe2f95b496a4e40ce0c8d1357c96/src/Config/IgnitionConfig.php#L146-L157
