### ISSUE TITLE
Conflict between Sentry and Ignition

### ISSUE THREAD

**Issue by byteasc** [spatie/laravel-ignition#30]
Not sure if this is your issue or a Sentry specific issue, but it wasn't a problem previously with the older version.

The reported error we're seeing is ```Cannot assign Sentry\Laravel\Tracing\ViewEngineDecorator to property Spatie\LaravelIgnition\Views\ViewExceptionMapper::$compilerEngine of type Illuminate\View\Engines\CompilerEngine```

**Comment by Wit3** [comment]
me too, same problem

**Comment by atmonshi** [comment]
getting the same:
```
Cannot assign Sentry\Laravel\Tracing\ViewEngineDecorator to property Spatie\LaravelIgnition\Views\ViewExceptionMapper::$compilerEngine of type Illuminate\View\Engines\CompilerEngine
```

**Comment by atmonshi** [comment]
It seems like it only happens on errors from blade only

to reproduce:

```
laravel new app
composer require sentry/sentry-laravel
```

open `welcome.blade.php`
add the code: `@dump()` anywhere.

visit `app.test`
see:
```
Cannot assign Sentry\Laravel\Tracing\ViewEngineDecorator to property Spatie\LaravelIgnition\Views\ViewExceptionMapper::$compilerEngine of type Illuminate\View\Engines\CompilerEngine
```

test repo: https://github.com/atmonshi/sentry-ignition
live site: http://45.79.13.53

**Comment by freekmurze** [comment]
This is fixed in the latest release.

**Comment by mertasan** [comment]
@freekmurze Similar problems persist. For example, in exceptions that occur in Livewire components.

I created a PR #42
